version: 0.2


phases:
   install:
       #runtime-version
       runtime-versions:
         nodejs: 20


pre_build:
    commands:
    #commands to be executed
    - echo "Installing Dependencies..."
    - npm install

build: 
   #commands for build
   - echo Building...
   - npm run build


post_build:
   commands:
   #commands for uploading
   - echo Uploading files in the s3 bucket...
   - aws s3 sync build/ s3://patangbaazi --delete